### ISSUE TITLE
Alpha version source code for CM11?

### ISSUE THREAD

**Issue by ayildirim** [frma71/sbs#7]
Hi @frma71,

Can you share source code for CM11? maybe in a seperate branch?

I'm testing autoswitcher app. I had to fix "exported = true". But latest source code doesnt work on CM11 & Xperia Z1.

Thanks,

**Comment by ayildirim** [comment]
I managed to get it working.

I used lib.so file from initial release. Then I combined it with latest surfaceflinger file and renamed cm11m12 to cm11 everywhere. It worked :+1:

**Comment by zagarolo** [comment]
Hi oneplus one work whit cm12 and cm11s SBS android version   play store
Il 13/apr/2015 19:30, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by ayildirim** [comment]
Hi @zagarolo,

I finished Automatic SBS Switcher. I published on PlayStore. It will be available soon.

When @frma71, fixes "exported" to true for SBS Service. It will work directly.

Until that, you can download source code from :
https://github.com/ayildirim/sbs/tree/patch-1
Then compile and install this on your phone. It will work together with Automatic SBS Switcher.

Automatic SBS Switcher will be here soon:
https://play.google.com/store/apps/details?id=com.mclightning.autosbs

Thanks,

**Comment by zagarolo** [comment]
Hi are not very good at compiling and can send apk my email? thank you very
Il 13/apr/2015 21:05, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by zagarolo** [comment]
Hi you have changed the lens correction ?
Il 13/apr/2015 21:05, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by zagarolo** [comment]
Hi you have changed the lens correction type trinus gyre ?
Il 13/apr/2015 21:05, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by zagarolo** [comment]
Hi is possible send e-mail apk ? Thanks
Il 13/apr/2015 21:05, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by ayildirim** [comment]
Hi @zagarolo,

AndroidSBS app is developed by Fredrik, not by me. I don't know about lens correction issue.

For your other questions to him, please start another issue thread.

About APK, I can compile one for you soon when I have time ;)

Thanks

**Comment by zagarolo** [comment]
Hi OK send apk my e-mail thanks
Il 13/apr/2015 23:00, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by zagarolo** [comment]
hi compile apk for my ? 😊 thanks






Inviata da Windows Mail





Da: Ahmet YILDIRIM
Data invio: ‎lunedì‎ ‎13‎ ‎aprile‎ ‎2015 ‎23‎:‎00
A: frma71/sbs
Cc: Leonardo Stagni





Hi @zagarolo,

AndroidSBS app is developed by Fredrik, not by me. I don't know about lens correction issue.

For your other questions to him, please start another issue thread.

About APK, I can compile one for you soon when I have time ;)

Thanks

**Comment by ayildirim** [comment]
Hi @zagarolo,

I'm waiting for Google to finish approval.

I uploaded it on Playstore. It will be online very soon!

thanks,

**Comment by zagarolo** [comment]
OK perfect thanks
Il 14/apr/2015 14:29, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by ayildirim** [comment]
Hi @zagarolo,

It is online now.
https://play.google.com/store/apps/details?id=com.mclightning.autosbs

You need the latest version of AndroidSBS. You can compile & install from this github repository. 

Otherwise, you need to wait for new version. @frma71  will release it soon.

Thanks,

**Comment by zagarolo** [comment]
Hi OK buy your app very thanks
Il 14/apr/2015 16:32, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:
